name: Docker Build and Push

on:
  release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: KoalaBotUK/docker-KoalBot
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            - jaydwee/koalabot:latest
            - jaydwee/koalabot:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push release
        if: ${{ github.event_name == 'prerelease' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            - jaydwee/koalabot:prerelease
            - jaydwee/koalabot:${{ steps.get_version.outputs.VERSION }}